# Generated by Django 3.2.4 on 2021-06-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=200)),
                ('port', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=100)),
                ('connect', models.IntegerField(default=0)),
                ('chequeSum', models.IntegerField(default=0)),
                ('cashout', models.IntegerField(default=0)),
                ('walletScan', models.CharField(max_length=100)),
                ('chequeScan', models.CharField(max_length=100)),
            ],
        ),
    ]
