# Generated by Django 3.2.4 on 2021-07-02 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=200)),
                ('port', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NodeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(max_length=100)),
                ('connect', models.IntegerField(default=0)),
                ('chequeSum', models.IntegerField(default=0)),
                ('cashout', models.IntegerField(default=0)),
                ('walletScan', models.TextField(null=True)),
                ('chequeScan', models.TextField(null=True)),
                ('uncashed', models.TextField(null=True)),
                ('node_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.nodeinfo')),
            ],
        ),
    ]
